"""Database models for the Virtual Company AI Agent Platform.

All entities use immutable UUID primary keys and carry created/updated
timestamps. Company boundaries are enforced in the service layer
(see security.py: scoped queries) as well as here via FK constraints.
"""

from __future__ import annotations

import datetime as dt
import os
import uuid
from pathlib import Path

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    create_engine,
    event,
    text as _sqltext,
)
from sqlalchemy.orm import declarative_base, relationship, sessionmaker

# NEXACREW_DB_PATH lets tests (see tests/conftest.py) point at a throwaway
# database instead of the live platform.db.
DB_PATH = Path(os.environ.get("NEXACREW_DB_PATH", "")
               or Path(__file__).resolve().parent.parent / "data" / "platform.db")
DB_PATH.parent.mkdir(parents=True, exist_ok=True)

engine = create_engine(f"sqlite:///{DB_PATH}", connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)
Base = declarative_base()


def _uuid() -> str:
    return uuid.uuid4().hex


def _now() -> dt.datetime:
    return dt.datetime.utcnow()


class TimestampMixin:
    id = Column(String, primary_key=True, default=_uuid)
    created_at = Column(DateTime, default=_now)
    updated_at = Column(DateTime, default=_now, onupdate=_now)
    archived_at = Column(DateTime, nullable=True)
    deleted_at = Column(DateTime, nullable=True)


class User(TimestampMixin, Base):
    __tablename__ = "users"
    username = Column(String, unique=True, nullable=False)
    display_name = Column(String, default="")
    password_hash = Column(String, nullable=False)
    is_admin = Column(Boolean, default=False)  # least privilege — admins are explicit
    company_owner_id = Column(String, default="")  # multi-company servers: the owner
                                                   # (tenant) this worker belongs to —
                                                   # set at HR enrollment; "" = unbound


class LicenseKey(TimestampMixin, Base):
    """Client-install license keys. Generated by an administrator on the
    server; each client computer must claim an unused key before it may
    install / use the program. A key binds to the first IP that claims it."""
    __tablename__ = "license_keys"
    key = Column(String, unique=True, nullable=False)
    note = Column(String, default="")               # admin label, e.g. "Peter's laptop"
    used = Column(Boolean, default=False)
    used_by_ip = Column(String, default="")
    used_by_host = Column(String, default="")       # client hostname (self-reported)
    used_at = Column(DateTime, nullable=True)
    last_seen_at = Column(DateTime, nullable=True)  # updated on client contact
    revoked = Column(Boolean, default=False)
    client_version = Column(String, default="")    # program version the client reported
    client_os = Column(String, default="")         # client OS (self-reported)
    client_hw = Column(Text, default="{}")         # hardware inventory JSON: mac,
                                                   # cpu_serial, disk_serial, ip, os…
    client_config = Column(Text, default="{}")     # admin-pushed remote config (JSON)
    config_rev = Column(Integer, default=0)        # bumped on every config push


class ClientDevice(TimestampMixin, Base):
    """Browser-based devices (phones / tablets / Chromebooks) that use the
    station or kiosk web pages without installing the client program. They
    self-register and beacon their device information so administrators see
    every connected device — mobile AND desktop — in the Clients panel."""
    __tablename__ = "client_devices"
    device_uid = Column(String, unique=True, nullable=False)  # browser-generated stable id
    kind = Column(String, default="mobile")        # mobile | tablet | desktop-browser
    usage = Column(String, default="")             # e.g. station:FRM-CHR-TEST-001 / kiosk:pos
    os = Column(String, default="")                # from user agent (iOS 17 / Android 14 / ChromeOS)
    model = Column(String, default="")             # device model hint from UA
    ua = Column(Text, default="")                  # full user agent
    ip = Column(String, default="")
    mac = Column(String, default="")               # WiFi MAC — browsers cannot expose it;
                                                   # kept for admin manual entry / future MDM
    license_key = Column(String, default="")       # optional license association
    user_name = Column(String, default="")         # signed-in operator
    last_seen_at = Column(DateTime, nullable=True)


class Workspace(TimestampMixin, Base):
    __tablename__ = "workspaces"
    name = Column(String, nullable=False)
    owner_id = Column(String, ForeignKey("users.id"), nullable=False)


class VirtualCompany(TimestampMixin, Base):
    __tablename__ = "companies"
    workspace_id = Column(String, ForeignKey("workspaces.id"), nullable=False)
    owner_user_id = Column(String, ForeignKey("users.id"), nullable=True)  # per-user isolation
    name = Column(String, nullable=False)
    logo = Column(String, default="🏢")
    description = Column(Text, default="")
    industry = Column(String, default="")
    website = Column(String, default="")
    address = Column(String, default="")
    timezone = Column(String, default="America/Los_Angeles")
    mission = Column(Text, default="")
    operating_principles = Column(Text, default="")
    brand_voice = Column(Text, default="")
    ai_instructions = Column(Text, default="")

    departments = relationship("Department", backref="company")
    employees = relationship("VirtualEmployee", backref="company")
    projects = relationship("Project", backref="company")


class Department(TimestampMixin, Base):
    __tablename__ = "departments"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    name = Column(String, nullable=False)
    parent_id = Column(String, ForeignKey("departments.id"), nullable=True)


class VirtualEmployee(TimestampMixin, Base):
    __tablename__ = "employees"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    department_id = Column(String, ForeignKey("departments.id"), nullable=True)
    manager_id = Column(String, ForeignKey("employees.id"), nullable=True)
    full_name = Column(String, nullable=False)
    avatar = Column(String, default="🧑‍💼")
    job_title = Column(String, default="")
    biography = Column(Text, default="")
    responsibilities = Column(Text, default="")
    skills = Column(Text, default="")
    goals = Column(Text, default="")
    working_style = Column(Text, default="")
    system_instructions = Column(Text, default="")
    status = Column(String, default="Active")  # Active/Inactive/On Leave/Archived
    # JSON list of permission strings
    permissions = Column(Text, default='["view","create","edit","draft_external"]')


class EmailIdentity(TimestampMixin, Base):
    __tablename__ = "email_identities"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    employee_id = Column(String, ForeignKey("employees.id"), nullable=False)
    provider = Column(String, default="local-dev")
    email_address = Column(String, nullable=False)
    display_name = Column(String, default="")
    signature = Column(Text, default="")
    verified = Column(Boolean, default=False)
    connection_status = Column(String, default="disconnected")
    encrypted_credentials = Column(Text, default="")  # Fernet-encrypted, never sent to client
    last_check_at = Column(DateTime, nullable=True)


class IntegrationConnection(TimestampMixin, Base):
    __tablename__ = "integration_connections"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    kind = Column(String, nullable=False)  # codex | email
    name = Column(String, default="")
    config = Column(Text, default="{}")
    encrypted_secret = Column(Text, default="")


class Project(TimestampMixin, Base):
    __tablename__ = "projects"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    name = Column(String, nullable=False)
    description = Column(Text, default="")
    status = Column(String, default="Active")
    priority = Column(String, default="Medium")
    start_date = Column(String, default="")
    due_date = Column(String, default="")
    tags = Column(Text, default="")
    instructions = Column(Text, default="")
    goals = Column(Text, default="")
    governance = Column(Text, default="{}")   # ISO 21500 governance artifacts (JSON)


class ProjectMember(TimestampMixin, Base):
    __tablename__ = "project_members"
    project_id = Column(String, ForeignKey("projects.id"), nullable=False)
    employee_id = Column(String, ForeignKey("employees.id"), nullable=False)


class Team(TimestampMixin, Base):
    """Named team of virtual employees with a lead — cross-project unit."""
    __tablename__ = "teams"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    name = Column(String, nullable=False)
    icon = Column(String, default="👥")
    mission = Column(Text, default="")
    lead_id = Column(String, ForeignKey("employees.id"), nullable=True)
    member_ids = Column(Text, default="[]")      # JSON list of employee ids
    status = Column(String, default="Active")    # Active / Standby / Archived


class Workflow(TimestampMixin, Base):
    """Ordered multi-stage process; each stage can be owned by a team or
    employee. Stages: JSON list of {name, owner_kind, owner_id, description,
    approval_required}."""
    __tablename__ = "workflows"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    name = Column(String, nullable=False)
    icon = Column(String, default="🔁")
    description = Column(Text, default="")
    trigger = Column(String, default="manual")   # manual / schedule / task_created
    stages = Column(Text, default="[]")
    diagram = Column(Text, default="{}")         # flow-chart designer: {nodes, edges}
    status = Column(String, default="Active")    # Active / Draft / Disabled


class SOP(TimestampMixin, Base):
    """Standard Operating Procedure — versioned controlled document."""
    __tablename__ = "sops"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    code = Column(String, default="")            # e.g. SOP-001
    title = Column(String, nullable=False)
    category = Column(String, default="General")
    version = Column(Integer, default=1)
    status = Column(String, default="Draft")     # Draft / In Review / Approved / Retired
    owner_id = Column(String, ForeignKey("employees.id"), nullable=True)
    purpose = Column(Text, default="")
    scope = Column(Text, default="")
    procedure = Column(Text, default="")         # markdown steps
    review_date = Column(String, default="")     # next scheduled review (YYYY-MM-DD)


class Shift(TimestampMixin, Base):
    """Worker schedule entry — recurring weekly shift or single assignment."""
    __tablename__ = "shifts"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    employee_id = Column(String, ForeignKey("employees.id"), nullable=False)
    name = Column(String, default="")            # e.g. "Morning duty"
    days = Column(Text, default="[]")            # JSON list of weekday ints 0=Mon
    start_time = Column(String, default="09:00")
    end_time = Column(String, default="17:00")
    date = Column(String, default="")            # set for one-off assignments (YYYY-MM-DD)
    role = Column(String, default="")            # duty during the shift
    notes = Column(Text, default="")
    status = Column(String, default="Active")    # Active / Paused


class TokenUsage(TimestampMixin, Base):
    """Per-run token consumption, one row per (run, agent/model)."""
    __tablename__ = "token_usage"
    user_id = Column(String, ForeignKey("users.id"), nullable=True)
    company_id = Column(String, ForeignKey("companies.id"), nullable=True)
    run_id = Column(String, nullable=True)
    agent = Column(String, nullable=False)        # codex / claude_code / api:<name> / copilot_relay
    input_tokens = Column(Integer, default=0)
    output_tokens = Column(Integer, default=0)
    calls = Column(Integer, default=1)


class Chat(TimestampMixin, Base):
    __tablename__ = "chats"
    company_id = Column(String, ForeignKey("companies.id"), nullable=True)
    project_id = Column(String, ForeignKey("projects.id"), nullable=True)
    owner_user_id = Column(String, ForeignKey("users.id"), nullable=True)  # per-user isolation
    title = Column(String, default="New chat")
    active_employee_id = Column(String, ForeignKey("employees.id"), nullable=True)


class Message(TimestampMixin, Base):
    __tablename__ = "messages"
    chat_id = Column(String, ForeignKey("chats.id"), nullable=False)
    role = Column(String, nullable=False)  # user | employee | system
    employee_id = Column(String, ForeignKey("employees.id"), nullable=True)
    content = Column(Text, default="")
    attachments = Column(Text, default="[]")  # JSON list of image/file paths
    project_id = Column(String, ForeignKey("projects.id"), nullable=True)  # project context at creation time


@event.listens_for(Message, "before_insert")
def _stamp_message_project(mapper, connection, target):  # noqa: ANN001
    """Record which project/workspace the message was produced under, so every
    response is permanently attributable even if the chat is re-linked later."""
    if target.project_id or not target.chat_id:
        return
    row = connection.execute(
        _sqltext("SELECT project_id FROM chats WHERE id = :c"), {"c": target.chat_id}
    ).first()
    if row and row[0]:
        target.project_id = row[0]


class Task(TimestampMixin, Base):
    __tablename__ = "tasks"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    project_id = Column(String, ForeignKey("projects.id"), nullable=True)
    title = Column(String, nullable=False)
    description = Column(Text, default="")
    status = Column(String, default="Backlog")
    priority = Column(String, default="Medium")
    assignee_id = Column(String, ForeignKey("employees.id"), nullable=True)


class AgentRun(TimestampMixin, Base):
    __tablename__ = "agent_runs"
    company_id = Column(String, ForeignKey("companies.id"), nullable=True)
    chat_id = Column(String, ForeignKey("chats.id"), nullable=True)
    employee_id = Column(String, ForeignKey("employees.id"), nullable=True)
    prompt = Column(Text, default="")
    status = Column(String, default="pending")  # pending/running/done/error
    result = Column(Text, default="")
    error = Column(Text, default="")


class ToolCall(TimestampMixin, Base):
    __tablename__ = "tool_calls"
    run_id = Column(String, ForeignKey("agent_runs.id"), nullable=False)
    tool = Column(String, nullable=False)
    arguments = Column(Text, default="{}")
    status = Column(String, default="pending")
    result = Column(Text, default="")


class ApprovalRequest(TimestampMixin, Base):
    __tablename__ = "approval_requests"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    employee_id = Column(String, ForeignKey("employees.id"), nullable=True)
    kind = Column(String, nullable=False)  # send_email | delete_data | ...
    summary = Column(Text, default="")
    payload_ref = Column(String, default="")  # e.g. EmailDraft id
    status = Column(String, default="pending")  # pending/approved/rejected/executed/failed
    decided_by = Column(String, ForeignKey("users.id"), nullable=True)
    decided_at = Column(DateTime, nullable=True)


class EmailDraft(TimestampMixin, Base):
    __tablename__ = "email_drafts"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    employee_id = Column(String, ForeignKey("employees.id"), nullable=False)
    identity_id = Column(String, ForeignKey("email_identities.id"), nullable=False)
    to = Column(Text, default="")
    cc = Column(Text, default="")
    bcc = Column(Text, default="")
    subject = Column(String, default="")
    body = Column(Text, default="")
    attachments = Column(Text, default="[]")  # JSON list of local file paths
    status = Column(String, default="draft")  # draft/awaiting_approval/sent/failed/cancelled
    idempotency_key = Column(String, unique=True, default=_uuid)


class EmailMessage(TimestampMixin, Base):
    __tablename__ = "email_messages"
    draft_id = Column(String, ForeignKey("email_drafts.id"), nullable=False)
    provider_message_id = Column(String, default="")
    sent_at = Column(DateTime, nullable=True)
    sender = Column(String, default="")
    recipients = Column(Text, default="")
    approved_by = Column(String, ForeignKey("users.id"), nullable=True)
    final_content = Column(Text, default="")


class InboxMessage(TimestampMixin, Base):
    """Internal mailbox — mail delivered to a virtual employee's identity."""
    __tablename__ = "inbox_messages"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    employee_id = Column(String, ForeignKey("employees.id"), nullable=False)
    from_address = Column(String, default="")
    to_address = Column(String, default="")
    subject = Column(String, default="")
    body = Column(Text, default="")
    read = Column(Integer, default=0)  # 0 = unread, 1 = read


class FileAsset(TimestampMixin, Base):
    __tablename__ = "file_assets"
    company_id = Column(String, ForeignKey("companies.id"), nullable=True)
    project_id = Column(String, ForeignKey("projects.id"), nullable=True)
    name = Column(String, nullable=False)
    path = Column(String, nullable=False)
    size = Column(Integer, default=0)


class KnowledgeSource(TimestampMixin, Base):
    __tablename__ = "knowledge_sources"
    company_id = Column(String, ForeignKey("companies.id"), nullable=False)
    name = Column(String, nullable=False)
    content = Column(Text, default="")


class Skill(TimestampMixin, Base):
    __tablename__ = "skills"
    name = Column(String, nullable=False)
    description = Column(String, default="")
    instructions = Column(Text, default="")  # injected into agent prompts
    target = Column(String, default="both")  # codex | claude | both
    enabled = Column(Boolean, default=True)
    owner_user_id = Column(String, ForeignKey("users.id"), nullable=True)  # per-user isolation


class AuditEvent(TimestampMixin, Base):
    __tablename__ = "audit_events"
    company_id = Column(String, ForeignKey("companies.id"), nullable=True)
    user_id = Column(String, ForeignKey("users.id"), nullable=True)
    employee_id = Column(String, ForeignKey("employees.id"), nullable=True)
    action = Column(String, nullable=False)
    detail = Column(Text, default="")
    prev_hash = Column(String, default="")  # tamper-evident chain
    entry_hash = Column(String, default="")


class Notification(TimestampMixin, Base):
    __tablename__ = "notifications"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    text = Column(Text, default="")
    read = Column(Boolean, default=False)


class ScheduledJob(TimestampMixin, Base):
    """Cron-scheduled agent task: at each matching time the prompt is sent to the chat."""
    __tablename__ = "scheduled_jobs"
    name = Column(String, nullable=False)
    cron = Column(String, nullable=False)          # "min hour dom month dow" (5-field cron)
    prompt = Column(Text, nullable=False)          # the task the agent must perform
    chat_id = Column(String, ForeignKey("chats.id"), nullable=False)
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    enabled = Column(Boolean, default=True)
    last_run_at = Column(DateTime, nullable=True)
    last_status = Column(String, default="")       # ok | error | ""


class CalendarAccount(TimestampMixin, Base):
    """External calendar connection (per user).
    provider: google | microsoft | apple | caldav | monday
    google/microsoft: OAuth (encrypted tokens) — user signs in with own account
    apple: CalDAV with Apple-ID + app-specific password
    caldav: any CalDAV server URL + username + password/API key
    monday: API key"""
    __tablename__ = "calendar_accounts"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    provider = Column(String, nullable=False)
    label = Column(String, default="")             # e.g. the account email
    config = Column(Text, default="{}")            # non-secret settings (calendar id, url, board id…)
    encrypted_secret = Column(Text, default="")    # Fernet: tokens / password / API key
    status = Column(String, default="connected")   # connected | error
    last_sync_at = Column(DateTime, nullable=True)
    last_error = Column(Text, default="")


class CalendarEvent(TimestampMixin, Base):
    """Local calendar event (per user); synchronized to all connected accounts."""
    __tablename__ = "calendar_events"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    description = Column(Text, default="")
    location = Column(String, default="")
    start_at = Column(DateTime, nullable=False)
    end_at = Column(DateTime, nullable=False)
    all_day = Column(Boolean, default=False)
    # remote ids per account: {"<account_id>": "<remote event id>", ...}
    remote_ids = Column(Text, default="{}")
    sync_status = Column(String, default="")       # "" | synced | partial | error


class MailAccount(TimestampMixin, Base):
    """Personal IMAP mailbox connection (per user) — the platform can read,
    search and manage real email from any provider.
    auth_method: password (LOGIN) | oauth2 (XOAUTH2 access token)"""
    __tablename__ = "mail_accounts"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    label = Column(String, default="")             # display name, e.g. the address
    imap_host = Column(String, nullable=False)
    imap_port = Column(Integer, default=993)
    use_ssl = Column(Boolean, default=True)
    auth_method = Column(String, default="password")   # password | oauth2
    username = Column(String, nullable=False)
    encrypted_secret = Column(Text, default="")    # Fernet: password / oauth token
    smtp_host = Column(String, default="")         # blank = guessed from imap_host
    smtp_port = Column(Integer, default=465)
    status = Column(String, default="connected")   # connected | error
    last_checked_at = Column(DateTime, nullable=True)
    last_error = Column(Text, default="")


class UserPhrase(TimestampMixin, Base):
    """Self-learned per-user vocabulary for operation prompts.
    Each user's personal wording (dialect, slang, shorthand — e.g. 睡郵 → check
    email) is learned from usage and applied before the built-in dictionary.
    source: taught (explicit “teach: X = y”) | auto (learned from habit)
    active: auto phrases activate after enough repeated confirmations."""
    __tablename__ = "user_phrases"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    phrase = Column(String, nullable=False)        # the user's own wording
    replacement = Column(String, nullable=False)   # english intent token(s)
    source = Column(String, default="taught")      # taught | auto
    hits = Column(Integer, default=0)              # observations (auto learning)
    active = Column(Boolean, default=True)
    last_used_at = Column(DateTime, nullable=True)

class BusinessProfile(TimestampMixin, Base):
    """Per-user deployment profile: personal vs commercial use.
    Commercial: industry type (restaurant / realtor / clinic / … or custom),
    an AI-generated professional instruction prompt that EVERY chat references,
    and learned SOP / ISO handbook documents."""
    __tablename__ = "business_profiles"
    user_id = Column(String, ForeignKey("users.id"), nullable=False, unique=True)
    usage_mode = Column(String, default="personal")    # personal | commercial
    company_type = Column(String, default="")          # key from templates or "custom"
    custom_type = Column(String, default="")           # free text when custom
    company_name = Column(String, default="")
    company_desc = Column(Text, default="")
    generated_prompt = Column(Text, default="")        # AI-generated instruction prompt
    prompt_status = Column(String, default="")         # "" | generating | ready | error
    docs = Column(Text, default="[]")                  # [{name,size,chars,at}]
    docs_text = Column(Text, default="")               # learned SOP/ISO text corpus
    license_key = Column(String, default="")           # per-company license — required
                                                       # when the server hosts multiple
                                                       # commercial companies


class BusinessRecord(TimestampMixin, Base):
    """Generic enterprise register row for the industry workspace modules
    (e.g. HACCP temperature log, policy renewals register, work orders …).
    data: JSON object with the module's fields."""
    __tablename__ = "business_records"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    module = Column(String, nullable=False)            # module key
    data = Column(Text, default="{}")
    status = Column(String, default="open")            # open | done | archived


class WarehouseMap(TimestampMixin, Base):
    """Facility / inventory map document — one row per warehouse zone.
    data: JSON {grid:{w,h,cell}, elements:[{id,type,x,y,w,h,rot,props}...]}
    where type ∈ rack|wall|door|dock|zone|office|staging|label and rack props
    carry the WMS addressing scheme (aisle, bays, levels, lot prefix) so every
    slot resolves to a location code AISLE-BAY-LEVEL like A01-03-L2."""
    __tablename__ = "warehouse_maps"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    warehouse = Column(String, default="Warehouse 1")
    zone = Column(String, default="Zone A")
    data = Column(Text, default="{}")
    status = Column(String, default="active")          # active | archived


class PosObject(TimestampMixin, Base):
    """Typed POS-server configuration object (restaurant & supermarket).
    kind: category | item | option_group | zone | table | department |
          togo | delivery_platform | kiosk | printer | drawer | pos_account |
          drawer_event | shift | order
    data: JSON with the kind's fields (layout coords for zones/tables, prices,
    variants, printer connection, drawer config, …)."""
    __tablename__ = "pos_objects"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    kind = Column(String, nullable=False)
    name = Column(String, default="")
    data = Column(Text, default="{}")
    parent_id = Column(String, default="")             # e.g. table → zone, item → category
    sort = Column(Integer, default=0)
    active = Column(Boolean, default=True)
    secret = Column(Text, default="")                  # encrypted credentials / device token


class Vendor(TimestampMixin, Base):
    """Purchasing vendor (supplier) master record."""
    __tablename__ = "vendors"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    name = Column(String, nullable=False)
    contact = Column(String, default="")
    phone = Column(String, default="")
    email = Column(String, default="")
    address = Column(Text, default="")
    terms = Column(String, default="Net 30")
    tax_id = Column(String, default="")
    default_account = Column(String, default="")       # default expense/inventory account
    status = Column(String, default="active")          # active | inactive
    notes = Column(Text, default="")


class PurchaseOrder(TimestampMixin, Base):
    """Purchase order with lifecycle + receiving state.
    lines: JSON [{sku, desc, qty, unit, unit_cost, received, damaged, ...}]"""
    __tablename__ = "purchase_orders_erp"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    po_number = Column(String, nullable=False)
    vendor_id = Column(String, ForeignKey("vendors.id"), nullable=True)
    lines = Column(Text, default="[]")
    tax = Column(Float, default=0.0)
    shipping = Column(Float, default=0.0)
    discount = Column(Float, default=0.0)
    total = Column(Float, default=0.0)
    expected = Column(DateTime, nullable=True)
    status = Column(String, default="draft")           # draft|pending approval|approved|sent|partially received|received|closed|cancelled
    notes = Column(Text, default="")


class VendorInvoice(TimestampMixin, Base):
    """Uploaded vendor invoice with AI extraction + MANDATORY human review.
    No invoice may post to accounting/inventory until a human explicitly
    confirms every required field (spec §16).
    extracted: JSON {field: {value, confidence, source}}  — confidence:
    high|medium|low|unreadable|missing|conflicting
    corrected: JSON {field: value} human-corrected values."""
    __tablename__ = "vendor_invoices"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    vendor_id = Column(String, ForeignKey("vendors.id"), nullable=True)
    po_id = Column(String, default="")
    file_path = Column(Text, default="")               # original file, never modified
    file_name = Column(String, default="")
    checksum = Column(String, default="")
    doc_type = Column(String, default="invoice")       # invoice|receipt|credit memo|statement|unsupported
    extracted = Column(Text, default="{}")
    corrected = Column(Text, default="{}")
    fields_confirmed = Column(Text, default="[]")      # list of confirmed field keys
    status = Column(String, default="uploaded")        # uploaded|processing|ai review required|matched|exception|pending approval|approved|posted|rejected|on hold
    confirm_statement = Column(Text, default="")       # signed confirmation text
    confirmed_by = Column(String, default="")
    confirmed_at = Column(DateTime, nullable=True)
    journal_id = Column(String, default="")            # posted journal entry
    notes = Column(Text, default="")


class Account(TimestampMixin, Base):
    """Chart-of-accounts entry (double-entry accounting)."""
    __tablename__ = "gl_accounts"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    number = Column(String, nullable=False)            # e.g. 1000
    name = Column(String, nullable=False)
    type = Column(String, nullable=False)              # asset|liability|equity|revenue|cogs|expense|other income|other expense
    parent = Column(String, default="")
    active = Column(Boolean, default=True)


class JournalEntry(TimestampMixin, Base):
    """Balanced double-entry journal entry.
    lines: JSON [{account, debit, credit, memo}] — total debits must equal
    total credits before posting; posted entries are corrected via reversal."""
    __tablename__ = "journal_entries"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    number = Column(Integer, default=0)
    at = Column(DateTime, nullable=True)
    memo = Column(Text, default="")
    lines = Column(Text, default="[]")
    source = Column(String, default="manual")          # manual|pos|purchasing|payroll|adjustment|reversal
    source_ref = Column(String, default="")            # linked record id
    status = Column(String, default="draft")           # draft|posted|reversed
    reversed_by = Column(String, default="")


# ============================================================
# Workforce, Visitor & Access Control platform
# (handoff/Enterprise_Workforce_Visitor_Access_POS_Prompt.md)
# ============================================================

class WorkerBadge(TimestampMixin, Base):
    """Worker QR badge credential. The QR payload is an opaque random token;
    only its SHA-256 hash is stored — no PII in the code, non-recoverable.
    Lifecycle: active → suspended|revoked|expired (revoked ids never reused)."""
    __tablename__ = "worker_badges"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)   # tenant
    worker_record_id = Column(String, default="")      # BusinessRecord id (workers module)
    worker_name = Column(String, default="")           # display only (shown to admins)
    token_hash = Column(String, nullable=False)        # sha256(opaque token)
    token_enc = Column(Text, default="")               # Fernet(token) — lets admins re-view/save the QR
    status = Column(String, default="active")          # active|suspended|revoked|expired
    issued_by = Column(String, default="")             # admin username
    expires_at = Column(DateTime, nullable=True)
    revoked_at = Column(DateTime, nullable=True)
    revoke_reason = Column(String, default="")
    last_used_at = Column(DateTime, nullable=True)
    last_used_site = Column(String, default="")
    lifecycle = Column(Text, default="[]")             # [{at,event,by,detail}] append-only


class DeviceEnrollment(TimestampMixin, Base):
    """Kiosk device enrollment. Admin issues a short-lived single-use code;
    the device exchanges it (TLS) for a device-bound credential (hash stored).
    kind: checkin (worker time kiosk) | visitor (visitor kiosk)"""
    __tablename__ = "device_enrollments"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    kind = Column(String, default="checkin")
    name = Column(String, default="")
    site = Column(String, default="")
    enroll_code_hash = Column(String, default="")      # sha256 of single-use code
    code_enc = Column(Text, default="")                # Fernet(code) — re-viewable while pending
    code_expires_at = Column(DateTime, nullable=True)
    credential_hash = Column(String, default="")       # sha256 of device credential
    enrolled_at = Column(DateTime, nullable=True)
    approved_by = Column(String, default="")
    status = Column(String, default="pending")         # pending|enrolled|revoked
    last_seen_at = Column(DateTime, nullable=True)
    client_info = Column(String, default="")


class TimePunch(TimestampMixin, Base):
    """Immutable raw time event — never updated or deleted; corrections are
    separate TimeAdjustment rows. Duplicate protection via idempotency key."""
    __tablename__ = "time_punches"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    worker_record_id = Column(String, default="")
    worker_name = Column(String, default="")
    badge_id = Column(String, default="")              # WorkerBadge id ("" = manual)
    device_id = Column(String, default="")             # DeviceEnrollment id
    site = Column(String, default="")
    event = Column(String, default="in")               # in|out|meal_start|meal_end|break_start|break_end
    at_utc = Column(DateTime, nullable=False)
    source = Column(String, default="badge")           # badge|manual|supervisor
    result = Column(String, default="ok")              # ok|duplicate|denied
    idempotency_key = Column(String, default="")
    note = Column(String, default="")


class TimeAdjustment(TimestampMixin, Base):
    """Audited correction referencing (not mutating) raw punches."""
    __tablename__ = "time_adjustments"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    worker_record_id = Column(String, default="")
    worker_name = Column(String, default="")
    day = Column(String, default="")                   # YYYY-MM-DD
    minutes_delta = Column(Integer, default=0)         # +/- minutes vs raw pairing
    reason = Column(Text, default="")
    requested_by = Column(String, default="")
    approved_by = Column(String, default="")
    status = Column(String, default="pending")         # pending|approved|rejected


class PayrollBatch(TimestampMixin, Base):
    """Approved-time → payroll conversion. Idempotent: one batch per
    (user, period) — re-running returns the existing batch, never duplicates.
    lines: JSON [{worker, regular_min, ot_min, adj_min, wage, gross}]."""
    __tablename__ = "payroll_batches"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    period_start = Column(String, default="")          # YYYY-MM-DD
    period_end = Column(String, default="")
    status = Column(String, default="draft")           # draft|approved|exported|posted
    lines = Column(Text, default="[]")
    total_gross = Column(Integer, default=0)           # cents
    approved_by = Column(String, default="")
    journal_id = Column(String, default="")            # accounting posting link
    export_checksum = Column(String, default="")


class Visit(TimestampMixin, Base):
    """Visitor registration + lifecycle. PII policy: identity numbers are
    Fernet-encrypted (id_number_enc), masked in every normal API response;
    the QR/visit badge exposes only an opaque code (hash stored)."""
    __tablename__ = "visits"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    visitor_name = Column(String, default="")          # display name (policy-permitted)
    company = Column(String, default="")               # visitor's organization (from)
    category = Column(String, default="walk-in")       # walk-in|preregistered|contractor|vendor|delivery|official
    host = Column(String, default="")
    purpose = Column(String, default="")
    destination = Column(String, default="")           # zone/department
    language = Column(String, default="en")
    consent_at = Column(DateTime, nullable=True)
    id_doc_type = Column(String, default="")           # none|drivers_license|passport|gov_id|org_badge
    id_number_enc = Column(Text, default="")           # encrypted, never returned raw
    face_photo = Column(Text, default="")              # JPEG data URI captured at kiosk (auto face capture)
    doc_images = Column(Text, default="[]")            # [file ids] (uploads dir, sanitized)
    status = Column(String, default="pending")         # pending|approved|denied|checked_in|checked_out|expired
    badge_code_hash = Column(String, default="")       # opaque visitor badge (issued on approval)
    badge_expires_at = Column(DateTime, nullable=True)
    approved_by = Column(String, default="")
    checked_in_at = Column(DateTime, nullable=True)
    checked_out_at = Column(DateTime, nullable=True)
    events = Column(Text, default="[]")                # append-only [{at,event,by}]


class DoorGate(TimestampMixin, Base):
    """Access-controlled door/gate behind a vendor-neutral adapter.
    NOTE: never overrides life-safety — decisions are advisory to hardware
    that must remain fail-safe per local fire code."""
    __tablename__ = "door_gates"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    name = Column(String, nullable=False)
    site = Column(String, default="")
    zone = Column(String, default="")
    mode = Column(String, default="badge")             # badge|badge+visitor|locked|open_hours
    schedule = Column(String, default="")              # "HH:MM-HH:MM" allowed window ("" = always)
    allow_visitors = Column(Boolean, default=False)
    active = Column(Boolean, default=True)
    health = Column(String, default="unknown")         # ok|offline|tamper|unknown


class AccessEvent(TimestampMixin, Base):
    """Immutable access decision log (allow/deny + machine-readable reason)."""
    __tablename__ = "access_events"
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    door_id = Column(String, default="")
    subject_kind = Column(String, default="worker")    # worker|visitor
    subject_id = Column(String, default="")            # badge id / visit id
    subject_name = Column(String, default="")
    decision = Column(String, default="deny")          # allow|deny
    reason = Column(String, default="")                # machine-readable code
    at_utc = Column(DateTime, nullable=False)

def init_db() -> None:
    Base.metadata.create_all(engine)
    # lightweight migration: add columns introduced after first release
    with engine.connect() as conn:
        from sqlalchemy import text
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(messages)"))]
        if "attachments" not in cols:
            conn.execute(text("ALTER TABLE messages ADD COLUMN attachments TEXT DEFAULT '[]'"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(email_drafts)"))]
        if "attachments" not in cols:
            conn.execute(text("ALTER TABLE email_drafts ADD COLUMN attachments TEXT DEFAULT '[]'"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(companies)"))]
        if "owner_user_id" not in cols:
            conn.execute(text("ALTER TABLE companies ADD COLUMN owner_user_id TEXT"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(chats)"))]
        if "owner_user_id" not in cols:
            conn.execute(text("ALTER TABLE chats ADD COLUMN owner_user_id TEXT"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(skills)"))]
        if "owner_user_id" not in cols:
            conn.execute(text("ALTER TABLE skills ADD COLUMN owner_user_id TEXT"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(license_keys)"))]
        if "client_version" not in cols:
            conn.execute(text("ALTER TABLE license_keys ADD COLUMN client_version TEXT DEFAULT ''"))
            conn.commit()
        if "client_os" not in cols:
            conn.execute(text("ALTER TABLE license_keys ADD COLUMN client_os TEXT DEFAULT ''"))
            conn.execute(text("ALTER TABLE license_keys ADD COLUMN client_config TEXT DEFAULT '{}'"))
            conn.execute(text("ALTER TABLE license_keys ADD COLUMN config_rev INTEGER DEFAULT 0"))
            conn.commit()
        if "client_hw" not in cols:
            conn.execute(text("ALTER TABLE license_keys ADD COLUMN client_hw TEXT DEFAULT '{}'"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(workflows)"))]
        if cols and "diagram" not in cols:
            conn.execute(text("ALTER TABLE workflows ADD COLUMN diagram TEXT DEFAULT '{}'"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(projects)"))]
        if cols and "governance" not in cols:
            conn.execute(text("ALTER TABLE projects ADD COLUMN governance TEXT DEFAULT '{}'"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(mail_accounts)"))]
        if cols and "smtp_host" not in cols:
            conn.execute(text("ALTER TABLE mail_accounts ADD COLUMN smtp_host TEXT DEFAULT ''"))
            conn.execute(text("ALTER TABLE mail_accounts ADD COLUMN smtp_port INTEGER DEFAULT 465"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(messages)"))]
        if cols and "project_id" not in cols:
            conn.execute(text("ALTER TABLE messages ADD COLUMN project_id TEXT"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(worker_badges)"))]
        if cols and "token_enc" not in cols:
            conn.execute(text("ALTER TABLE worker_badges ADD COLUMN token_enc TEXT DEFAULT ''"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(users)"))]
        if cols and "company_owner_id" not in cols:
            conn.execute(text("ALTER TABLE users ADD COLUMN company_owner_id TEXT DEFAULT ''"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(business_profiles)"))]
        if cols and "license_key" not in cols:
            conn.execute(text("ALTER TABLE business_profiles ADD COLUMN license_key TEXT DEFAULT ''"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(device_enrollments)"))]
        if cols and "code_enc" not in cols:
            conn.execute(text("ALTER TABLE device_enrollments ADD COLUMN code_enc TEXT DEFAULT ''"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(visits)"))]
        if cols and "face_photo" not in cols:
            conn.execute(text("ALTER TABLE visits ADD COLUMN face_photo TEXT DEFAULT ''"))
            conn.commit()
        cols = [r[1] for r in conn.execute(text("PRAGMA table_info(visits)"))]
        if cols and "company" not in cols:
            conn.execute(text("ALTER TABLE visits ADD COLUMN company TEXT DEFAULT ''"))
            conn.commit()
        # deployment runs out of Los Angeles — backfill the never-customized
        # UTC default so existing companies pick up the right local timezone
        conn.execute(text(
            "UPDATE companies SET timezone = 'America/Los_Angeles' "
            "WHERE timezone IS NULL OR timezone = '' OR timezone = 'UTC'"
        ))
        conn.commit()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
